- name: clone simulator repo 
  git:
      repo=https://review.gerrithub.io/davidsaOpenu/simulator
      accept_hostkey=yes
      recursive=no
      force=yes
      version=FETCH_HEAD
      refspec={{ ref }}
      dest={{ dest }}

- name: unmount tmpfs data
  become: true
  mount: state=unmounted src=tmpfs fstype=tmpfs name={{ dest }}/eVSSIM/QEMU/hw/data

- name: clean untracked files from repository
  shell: git clean -x -f -d -q chdir={{ dest }}

- name: create data
  file: path={{ dest }}/eVSSIM/tests/data state=directory
 
- name: create conf link
  shell: ln -sf ../../CONFIG/ssd.conf chdir={{ dest }}/eVSSIM/tests/data

- name: build ssd_monitor
  shell:
      qmake -o Makefile ssd_monitor_p.pro && make
      chdir={{ dest }}/eVSSIM/MONITOR/SSD_MONITOR_PM
  when: build_ssd_monitor

- name: compile osc-osd
  shell: make target_clean && make target chdir={{ dest }}/eVSSIM/osc-osd
