- name: build unit tests
  shell: "make mklink && make all"
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: build_unit_tests

- name: run sector tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./sector_tests --ci
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: sector_tests
  async: 7200 #secs = 2 hours
  poll: 60 #secs

- name: run object tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./object_tests
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: object_tests
  async: 1200 #secs = 20 min
  poll: 60 #secs



- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
