- name: build unit tests - make mklink
  make: 
    chdir: "{{ dest }}/eVSSIM/tests"
    target: mklink
  register: build_unit_tests_mklink

- name: build unit tests - make all
  make:
    chdir: "{{ dest }}/eVSSIM/tests"
    target: all
  register: build_unit_tests_all

- debug: msg="Done  build unit tests"

- name: run sector tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./sector_tests --ci
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: sector_tests

- name: run object tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./object_tests
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: object_tests

- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
