- name: build host tests
  shell: "make distclean && make mklink && bear make"
  args:
      chdir: "{{ dest }}/eVSSIM/tests/host"

- name: run host tests
  shell: ./run_all_host_tests.sh
  args:
      chdir: "{{ dest }}/eVSSIM/tests/host"
  register: host_tests

- debug: msg="Host tests stdout\n{{ host_tests.stdout }}"
- debug: msg="Host tests stderr\n{{ host_tests.stderr }}"

- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
