- name: build unit tests
  shell: make chdir={{ dest }}/eVSSIM/tests
  register: build_unit_tests

- name: run sector tests
  shell: ./sector_tests --ci chdir={{ dest }}/eVSSIM/tests
  register: sector_tests

- name: run object tests
  shell: ./object_tests --ci chdir={{ dest }}/eVSSIM/tests
  register: object_tests

- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
