- name: get gtest
  unarchive: src=https://github.com/google/googletest/archive/release-1.7.0.tar.gz dest=/opt/ copy=no

- name: ensure /opt/gtest dir is empty
  file: path=/opt/gtest state=absent

- name: move googletest to gtest
  command: mv /opt/googletest-release-1.7.0 /opt/gtest

- name: create lib for gtest
  file: path=/opt/gtest/lib state=directory
 
- name: build gtest
  shell: cd /opt/gtest/lib && cmake .. && make

- name: build unit tests
  shell: make chdir={{ dest }}/eVSSIM/tests
  register: build_unit_tests

- name: run sector tests
  shell: ./sector_tests --ci chdir={{ dest }}/eVSSIM/tests
  register: sector_tests

- name: run object tests
  shell: ./object_tests --ci chdir={{ dest }}/eVSSIM/tests
  register: object_tests

- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
