- name: build unit tests
  shell: "make mklink && make all"
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: build_unit_tests

- name: run sector tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./sector_tests --ci
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: sector_tests
  async: 3600 #secs = 1 hour
  poll: 30 #secs

- name: run object tests
  shell: valgrind --leak-check=full --error-exitcode=2 ./object_tests
  args:
      chdir: "{{ dest }}/eVSSIM/tests"
  register: object_tests
  async: 600 #secs = 10 min
  poll: 30 #secs



- debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
