- name: install required packages
  apt: pkg={{ item }} state=installed
  with_items:
      - git
      # common gcc for Ubuntu 12.04 and Ubuntu 14.04
      # that manages to compile our ancient version of qemu
      - gcc-4.7
      # to build gtest
      - cmake
      - g++
      # to unzip hda.img.zip
      - unzip
      # to build osc-osd
      - libsqlite3-dev
      - zlib1g-dev
      - libgnutls-dev
      - libvncserver-dev
      - libpci-dev
      - libaio-dev
      - sshpass

- name: install packages for SSD monitor
  apt: pkg={{ item }} state=installed
  with_items:
      - libqt3-mt-dev
  when: build_ssd_monitor
