# Cleanup previous executions on this host
- include: qemu_stop.yml

- include: hda_image.yml
  - when: cleanup_only == false

- include: qemu_prepare.yml
  - when: cleanup_only == false

# Start Guest machine and confirm it is up
- include: qemu_start.yml
  - when: cleanup_only == false
