- name: create ssd.conf
  template:
    src: "ssd.conf"
    dest: "{{ dest }}/eVSSIM/QEMU/hw/data/ssd.conf"
  tags: qemu

- name: start guest
  shell: "../x86_64-softmmu/qemu-system-x86_64 -m {{memory}} -smp {{smp}} -hda '{{hda_img}}' -device nvme -redir tcp:{{guest_ssh_port}}::22 -nographic -vnc :0 -kernel '{{dest}}/{{kernel_image}}' -initrd '{{dest}}/{{initrd_image}}' -append '{{kernel_cmdline}}' -daemonize -pidfile '{{qemu_pid_file}}' -machine {{qemu_machine}}"
  args:
    chdir: "{{ dest }}/eVSSIM/QEMU/hw"
  tags: qemu

- name: waiting for guest to start
  wait_for:
  args:
    port: "{{guest_ssh_port}}"
    search_regex: OpenSSH
    timeout: 10000
  tags: qemu

- name: ssh into guest
  shell: "{{ guest_ssh_cmd }} uname"
  register: guest_uname
  tags: qemu

- debug:
  args:
    msg: "Output of 'ssh uname' to guest: {{ guest_uname.stdout }}"
  tags: qemu

# XXX: change to be generic
- name: Transfer file from local_host to guest_host
  shell: sshpass -p esd scp -o "StrictHostKeyChecking=no" -P 2222 fio_tests.tar esd@127.0.0.1:~
  args:
    chdir: "{{ dest }}/eVSSIM"

- debug: msg="Done starting and preparing guest machine"
  tags: qemu
