---
- hosts: localhost
  connection: local
 
# Usage:
#
# ansible-playbook hosttests.yml -e ref=refs/changes/53/271953/1
#

  vars:
    - dest: ../target/simulator
    - ref: refs/heads/master

  tasks:
    - name: clone simulator repo 
      git:
          repo=https://review.gerrithub.io/davidsaOpenu/simulator
          accept_hostkey=yes
          recursive=no
          force=yes
          version=FETCH_HEAD
          refspec={{ ref }}
          dest={{ dest }}

    - name: clean untracked files from repository
      shell: git clean -x -f -d -q chdir={{ dest }}

    - name: create data
      file: path={{ dest }}/eVSSIM/tests/data state=directory
     
    - name: rm conf link
      file: path={{ dest }}/eVSSIM/tests/data/ssd.conf 
            state=absent
  
    - name: create conf link
      shell: ln -s ../../CONFIG/ssd.conf chdir={{ dest }}/eVSSIM/tests/data

    - name: build ssd_monitor
      shell: qmake -o Makefile ssd_monitor_p.pro && make chdir={{ dest }}/eVSSIM/MONITOR/SSD_MONITOR_PM

    - name: compile osc-osd
      shell: make target_clean && make target chdir={{ dest }}/eVSSIM/osc-osd 

    - name: make links
      shell: make mklink chdir={{ dest }}/eVSSIM/tests
      ignore_errors: yes

    - name: build unit tests
      shell: make chdir={{ dest }}/eVSSIM/tests
      register: build_unit_tests
      failed_when: build_unit_tests.rc == 1
   
    # XXX: run with param 
    - name: run sector tests
      shell: ./sector_tests chdir={{ dest }}/eVSSIM/tests
      register: sector_tests
      failed_when: sector_tests.rc == 1
 
    # XXX: run with param 
    - name: run object tests
      shell: ./object_tests chdir={{ dest }}/eVSSIM/tests
      register: object_tests
      failed_when: object_tests.rc == 1

    - debug: msg="Done running tests on {{ ref }}, target is in {{ dest }}"
 
