---
- hosts: localhost
  connection: local
 
  # Variables:
  # pr - specify the pr to pull. example: ansible-playbook hosttests.yml -e pr=refs/changes/53/271953/1

  vars:
    - destination: ../target/simulator

  tasks:
    - name: rm prev target
      file: path={{ destination }}
            state=absent

    - name: clone simulator repo 
      git: repo=https://review.gerrithub.io/davidsaOpenu/simulator accept_hostkey=yes recursive=no dest={{ destination }}

    - name: git reset  
      shell: git reset --hard HEAD chdir={{ destination }}
   
    - name: git clean
      shell: git clean -x -f -d -q chdir={{ destination }}

    - name: git pull PR
      shell: git pull origin {{ pr }} chdir={{ destination }}
      when: pr is defined
   
    - name: create data
      file: path={{ destination }}/eVSSIM/tests/data state=directory
     
    - name: rm conf link
      file: path={{ destination }}/eVSSIM/tests/data/ssd.conf 
            state=absent
  
    - name: create conf link
      shell: cd {{ destination }}/eVSSIM/tests/data; ln -s ../../CONFIG/ssd.conf

    - name: compile osc-osd
      shell: cd {{ destination }}/eVSSIM/osc-osd/; make target_clean; make target

    - name: make links
      shell: cd {{ destination }}/eVSSIM/tests/; make mklink
      ignore_errors: yes

    - name: build unit tests
      shell: cd {{ destination }}/eVSSIM/tests/; make 
      register: build_unit_tests
    
    #  XXX: print error messages if any
    #- debug: var=build_unit_tests.stdout_lines
 
