---
- hosts: localhost
  connection: local
  become: true
 
  tasks:
    - name: install required packages
      apt: pkg={{ item }} state=installed
      with_items:
          - git
          - cmake
          - sqlite
          - g++
          - libqt3-mt-dev
          - zlib1g-dev
          - libgnutls-dev
          - libvncserver-dev
          - libpci-dev
          - libaio-dev
          - sshpass

    - name: get gtest
      unarchive: src=https://github.com/google/googletest/archive/release-1.7.0.tar.gz dest=/opt/ copy=no
   
    - name: ensure /opt/gtest dir is empty
      file: path=/opt/gtest state=absent
    
    - name: move googletest to gtest
      command: mv /opt/googletest-release-1.7.0 /opt/gtest
 
    - name: create lib for gtest
      file: path=/opt/gtest/lib state=directory
     
    - name: build gtest
      shell: cd /opt/gtest/lib && cmake .. && make
