- name: configure prerequisites
  hosts: [host_testers, guest_testers]
  roles:
    - common
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    https_proxy: "{{ lookup('env','http_proxy') }}"
  tags: [host, guest]

- name: perform host tests
  hosts: host_testers
  roles:
    - host_tester
  tags: host

- name: perform guest tests setup
  hosts: guest_testers
  roles:
    - guest_tester_pre
  tags: guest

- name: perform guest tests
  hosts: guests
  roles:
    - guest_tester
  tags: guest

- name: perform guest tests cleanup
  hosts: guest_testers
  roles:
    - { role: simulator, cleanup_only: true} 
  tags: guest
