---
#
# Pull elasticsearch image and initiate container
#

- name: Start elasticsearch container, connect to network
  docker_container:
   name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
   hostname: elasticsearch
   state: started
   auto_remove: yes
   ports:
    - "9200:9200"
    - "9300:9300"
   env:
       http.host: 0.0.0.0
       transport.host: 127.0.0.1
