---
#
# Pull Filebeat and start container
#

- name: Start filebeat container, connect to network and link
  docker_container:
   name: filebeat
   image: docker.elastic.co/beats/filebeat:5.6.2
   hostname: filebeat
   state: started
   auto_remove: yes
   links:
    - "logstash:logstash"
   volumes:
    - "{{ ansible_env.HOME }}/elk-config/filebeat/logs:/usr/share/filebeat/log_d"
    - "{{ ansible_env.HOME }}/elk-config/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml"
