---
#
# Pull Kibana and start container
#

- name: Start kibana container, connect to network and link
  docker_container:
   name: kibana
   image: docker.elastic.co/kibana/kibana:5.6.2
   hostname: kibana
   state: started
   auto_remove: yes
   links:
    - "elasticsearch:elasticsearch"
   ports:
    - "5601:5601"
