---
#
# Pull Logstash and start container
#

- name: Start logstash container, connect to network and link
  docker_container:
   name: logstash
   image: docker.elastic.co/logstash/logstash:5.6.2
   hostname: logstash
   state: started
   auto_remove: yes
   links:
    - "elasticsearch:elasticsearch"
   volumes:
    - "{{ ansible_env.HOME }}/elk-config/logstash/pipeline:/usr/share/logstash/pipeline"
