# task for creating directory for logstash and copying config

- name: Create logstash directory
  file:
    path: "{{ ansible_env.HOME }}/elk-config/logstash/pipeline"
    state: directory
    recurse: yes
- name: Copy logstash config file
  copy:
    src: logstash.conf
    dest: "{{ ansible_env.HOME }}/elk-config/logstash/pipeline/logstash.conf"

# tasks for creating directories for filebeat

- name: Create filebeat config directory
  file:
    path: "{{ ansible_env.HOME }}/elk-config/filebeat/config"
    state: directory
    recurse: yes

- name: Create filebeat logs directory
  file:
    path: "{{ ansible_env.HOME }}/elk-config/filebeat/logs"
    state: directory
    recurse: yes

- name: Copy filebeat config file
  copy:
    src: filebeat.yml
    dest: "{{ ansible_env.HOME }}/elk-config/filebeat/config/filebeat.yml"

#include the role that creates elasticsearch docker container
- include: elasticsearch.yml

#include the role that creates kibana docker container
- include: kibana.yml

#include the role that creates logstash docker container
- include: logstash.yml

#include the role that creates filebeat docker container
- include: filebeat.yml
